### ISSUE TITLE
format row trourght reg expression or template string

### ISSUE THREAD

**Issue by stefanocudini** [dmitmel/telegraf-update-logger#11]
hi

this form my logs
```
2020-10-30T20:01:11.408Z [1759] Stef: /list
```

I want in this format:
```
2020-10-30T20:01:11.408Z [1759] user: "Stef" command: /list
```

for only one reason.. greping my logs is difficult now..! I'd like to filter usernames in all logs

**Comment by dmitmel** [comment]
You have to change the format function to a custom one for this. There isn't really another way to add enough options to the default formatter to accommodate for every potential use-case. Here's the default formatter's code: https://github.com/dmitmel/telegraf-update-logger/blob/cc00ee0659bca2674fc3f56242f083a5041ff3d5/lib/format.js
