### ISSUE TITLE
[Question] How to use this middleware with other middleware

### ISSUE THREAD

**Issue by felinto-dev** [dmitmel/telegraf-update-logger#14]
Hi,

I would like to record all the user's actions and instead of sending it to a file or console.log it would be good to send it to a Telegram channel.

I know what logic I should follow to do this using my own middleware, but I would like a way to get the log provided by this middleware.

Perhaps this is an interesting feature as well.

**Comment by dmitmel** [comment]
```js
bot.use(updateLogger({
  colors: false,
  log: (str) => {
    bot.telegram.sendMessage(LOG_CHAT_ID, str);
  },
}));
```

**Comment by felinto-dev** [comment]
Hi,

Thanks for the answer!

Unfortunately, at the moment I cannot follow this approach. I'm using the wrapper for telegraf in nestjs
https://github.com/bukhalo/nestjs-telegraf#readme

And the BOT command is not available.

Does this middleware expose your log to "ctx."? That way I could access the log generated by him in the next middleware.

**Comment by dmitmel** [comment]
Unfortunately not. You can trivially write your own middleware function though:

```js
function customUpdateLogger(ctx, next) {
  let str = updateLogger.format(ctx.update, { colors: false });
  ctx.telegram.sendMessage(LOG_CHAT_ID, str);
  return next();
}
```

**Comment by felinto-dev** [comment]
I can't say how grateful I am for your help 🙏

Based on the code passed here I adapted it to my needs to be able to use it together with the wrapper for Telegraf in NestJS. I hope it can help someone.

app.module.ts
```ts
    TelegrafModule.forRootAsync({
      useFactory: async () => ({
        token: 'TELEGRAM BOT TOKEN',
        middlewares: [sendLogToChannel(LOG_CHAT_ID)],
      }),
      inject: [],
    }),
```

send-log-to-channel.ts
```ts
import * as updateLogger from 'telegraf-update-logger';
import { Context } from 'telegraf';

export const sendLogToChannel = (channelId: number) => (ctx: Context, next) => {
  const message = updateLogger.format(ctx.update, { colors: false });
  ctx.telegram.sendMessage(channelId, message);
  return next();
};

```
