### ISSUE TITLE
Log timestamps

### ISSUE THREAD

**Issue by baurmatt** [dmitmel/telegraf-update-logger#6]
Hey,

first of all: Thanks for this package, it works really great! The only thing I'm missing are timestamps. Is it possible to add them?

Thanks!

**Comment by dmitmel** [comment]
I believe the simplest solution is to use a custom logger function, e.g.:

```js
bot.use(updateLogger({ log: (str) => console.log(new Date().toISOString(), str) }));
```

**Comment by baurmatt** [comment]
Works like a charm! :) Thanks for your instant reaction! :)
