### ISSUE TITLE
Error with inline messages.

### ISSUE THREAD

**Issue by TheEdoRan** [dmitmel/telegraf-update-logger#9]
Hi, when I try to use the library with inline queries, I get this error:
```Failed to process updates. TypeError: Cannot read property 'message' of undefined```

Is there a way to enable logging for inline messages too?

**Comment by Autapomorph** [comment]
@theedoran see #5 
Also we should ask @dmitmel to publish new release

**Comment by dmitmel** [comment]
Sorry, forgot about this ticket. Give me a second, I'll publish a new release.

**Comment by dmitmel** [comment]
Just published version 1.2.0.
